"""Unit tests for the avatar pipeline's TTS audio cache — real filesystem
I/O against a pytest tmp_path, no model/network involved."""

from __future__ import annotations

from backend.app.models.tts import TTSRequest
from backend.app.services import tts_cache


def _request(**overrides) -> TTSRequest:
    defaults = dict(text="مرحبا", dialect_id="saudi")
    defaults.update(overrides)
    return TTSRequest(**defaults)


def test_identical_requests_produce_the_same_key():
    a = tts_cache.cache_key(_request(), model_repo_id="repo-v1", ref_audio_bytes=None)
    b = tts_cache.cache_key(_request(), model_repo_id="repo-v1", ref_audio_bytes=None)
    assert a == b


def test_different_text_produces_a_different_key():
    a = tts_cache.cache_key(_request(text="مرحبا"), model_repo_id="repo-v1", ref_audio_bytes=None)
    b = tts_cache.cache_key(_request(text="مرحبا بك"), model_repo_id="repo-v1", ref_audio_bytes=None)
    assert a != b


def test_different_model_version_produces_a_different_key():
    # The real requirement this guards: a model upgrade must never serve
    # stale audio generated by a previous model version under the same key.
    a = tts_cache.cache_key(_request(), model_repo_id="repo-v1", ref_audio_bytes=None)
    b = tts_cache.cache_key(_request(), model_repo_id="repo-v2", ref_audio_bytes=None)
    assert a != b


def test_different_ref_audio_bytes_produce_different_keys():
    req = _request(mode="clone", ref_text="hi")
    a = tts_cache.cache_key(req, model_repo_id="repo-v1", ref_audio_bytes=b"clip-one")
    b = tts_cache.cache_key(req, model_repo_id="repo-v1", ref_audio_bytes=b"clip-two")
    assert a != b


def test_get_returns_none_when_absent(tmp_path):
    assert tts_cache.get(tmp_path, "nonexistent-key") is None


def test_put_then_get_roundtrips(tmp_path):
    path = tts_cache.put(tmp_path, "some-key", b"RIFF-fake-wav-bytes")
    assert path.exists()
    assert path.read_bytes() == b"RIFF-fake-wav-bytes"
    assert tts_cache.get(tmp_path, "some-key") == path
