"""Content-addressed disk cache for generated TTS audio.

Scoped to the avatar job pipeline (`services/avatar_jobs.py`) only — the
existing standalone `/api/tts` endpoint is untouched (each call there still
always regenerates, exactly as before "do not rewrite unrelated working
functionality"). An avatar job's audio step is a natural place for this
cache to actually pay off: `/api/tts/avatar/jobs/{id}/cancel` and retries
after a downstream (video-encoding) failure would otherwise re-run the TTS
model for identical text/voice for no reason.

The cache key folds in `model_repo_id` (from `Settings`) specifically so a
future model upgrade can't serve stale audio generated by a different
model under the same key — matches this app's existing "model version"
sensitivity the brief's own caching section asks for.
"""

from __future__ import annotations

import hashlib
from pathlib import Path

from backend.app.models.tts import TTSRequest


def cache_key(request: TTSRequest, *, model_repo_id: str, ref_audio_bytes: bytes | None) -> str:
    """Deliberately excludes `ai_dialect_rewrite` from the key material:
    that flag only affects what `working_text` OpenAI hands back *before*
    this request's own `.text` is set — by the time a `TTSRequest` reaches
    here (already carrying its final `.text`), two requests with identical
    resulting text/voice fields but a different `ai_dialect_rewrite` value
    are asking the model for genuinely identical audio."""
    parts = [
        request.text,
        request.mode,
        request.dialect_id,
        request.gender or "",
        request.pitch,
        request.ref_text or "",
        f"{request.speed:.3f}",
        request.quality,
        f"{request.guidance_scale:.3f}",
        model_repo_id,
    ]
    digest = hashlib.sha256("\x1f".join(parts).encode("utf-8"))
    if ref_audio_bytes:
        digest.update(ref_audio_bytes)
    return digest.hexdigest()


def get(cache_dir: Path, key: str) -> Path | None:
    path = cache_dir / f"{key}.wav"
    return path if path.exists() else None


def put(cache_dir: Path, key: str, wav_bytes: bytes) -> Path:
    cache_dir.mkdir(parents=True, exist_ok=True)
    path = cache_dir / f"{key}.wav"
    # Write-then-rename: a concurrent job computing the same key never
    # observes a partially-written file at the final path.
    tmp = cache_dir / f".{key}.wav.tmp"
    tmp.write_bytes(wav_bytes)
    tmp.replace(path)
    return path
