"""Content-addressed disk cache for generated TTS audio.

Scoped to the avatar job pipeline (`services/avatar_jobs.py`) only — the
existing standalone `/api/tts` endpoint is untouched (each call there still
always regenerates, exactly as before "do not rewrite unrelated working
functionality"). An avatar job's audio step is a natural place for this
cache to actually pay off: `/api/tts/avatar/jobs/{id}/cancel` and retries
after a downstream (video-encoding) failure would otherwise re-run the TTS
model for identical text/voice for no reason.

The cache key folds in `model_repo_id` (from `Settings`) specifically so a
future model upgrade can't serve stale audio generated by a different
model under the same key — matches this app's existing "model version"
sensitivity the brief's own caching section asks for.
"""

from __future__ import annotations

import hashlib
from pathlib import Path

from backend.app.models.tts import TTSRequest


def cache_key(request: TTSRequest, *, model_repo_id: str, ref_audio_bytes: bytes | None) -> str:
    """Called in `avatar_jobs.py::_synthesize_audio` *before*
    `SpeechPipeline.synthesize()` runs — so `request.text` here is still the
    raw, un-rewritten text, and the AI dialect rewrite step (automatic
    inside `synthesize()`, see `dialect_rewriter.py`) never even runs on a
    cache hit. That's deliberate, not an oversight: two jobs with identical
    raw text/dialect/voice fields are the same request as far as this cache
    is concerned, and reusing the first one's audio means the second one
    pays for neither the OpenAI rewrite call nor the TTS model call — the
    real cost saving this cache exists for."""
    parts = [
        request.text,
        request.mode,
        request.dialect_id,
        request.gender or "",
        request.pitch,
        request.ref_text or "",
        f"{request.speed:.3f}",
        request.quality,
        f"{request.guidance_scale:.3f}",
        model_repo_id,
    ]
    digest = hashlib.sha256("\x1f".join(parts).encode("utf-8"))
    if ref_audio_bytes:
        digest.update(ref_audio_bytes)
    return digest.hexdigest()


def get(cache_dir: Path, key: str) -> Path | None:
    path = cache_dir / f"{key}.wav"
    return path if path.exists() else None


def put(cache_dir: Path, key: str, wav_bytes: bytes) -> Path:
    cache_dir.mkdir(parents=True, exist_ok=True)
    path = cache_dir / f"{key}.wav"
    # Write-then-rename: a concurrent job computing the same key never
    # observes a partially-written file at the final path.
    tmp = cache_dir / f".{key}.wav.tmp"
    tmp.write_bytes(wav_bytes)
    tmp.replace(path)
    return path
